name: .NET Web API CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Instalacja .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Przywracanie pakietów NuGet
        run: dotnet restore

      - name: Budowanie aplikacji
        run: dotnet build --configuration Release --no-restore