name: Deploy Azure Infrastructure (Bicep)

on:
  push:
    branches:
      - feature/bicep-infrastructure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: rg-ecommerce-api
          template: ./infra/main.bicep
          parameters: ./infra/main.parameters.json